[package]
name = "home_keeper"
version = "0.1.0"
authors = ["Muhannad Alrusayni <0x3UH4224D@gmail.com>"]
license = "GPL3+"

[dependencies]
gettext-rs = "0.3.0"

[dependencies.gio]
git = "https://github.com/gtk-rs/gio"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
